
--CREATE THE SALES TABLE --
CREATE TABLE SALES_TREND(
SALES_DATE DATE,
POS INT,
CASH INT
);

--VIEW THE SALES RECORD TABLE --
SELECT * 
FROM SALES_TREND;

--VALIDATE THE DATE RANGE AND NUMBER OF RECORD --
SELECT
    MIN(SALES_DATE) AS Earliest_Date,
    MAX(SALES_DATE) AS Latest_Date,
    COUNT(*) AS Total_Rows
FROM SALES_TREND;

--CHECK THE YEARS AND MONTH PRESENT IN THE DATASET--
SELECT DISTINCT
    YEAR(SALES_DATE) AS Sales_Year,
    MONTH(SALES_DATE) AS Sales_Month
FROM SALES_TREND
ORDER BY
    Sales_Year,
    Sales_Month;

